import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "EXTINCT",
    name: "Red Handfish",
    price: "300",
    categoryName: "Fauna",
    img: "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/red-handfish-thymichthys-c2-a0politus-rare-and-critically-news-photo-1628801894.jpg?crop=0.97088xw:1xh;center,top&resize=980:*",
    description: "Lost 200 years ago",
    rating: "3.2",
  },
  {
    _id: uuid(),
    title: "Vulnerable",
    name: "Marine Iguanas",
    price: "750",
    categoryName: "Fauna",
    img: "https://files.worldwildlife.org/wwfcmsprod/images/Marine_Iguana_Portrait/story_full_width/943c3pnxb6_Medium_WW288384.jpg",
    description: "World's only ocean-going lizards",
    rating: "3.7",
  },
  {
    _id: uuid(),
    title: "EXTINCT",
    name: "Golden Toad",
    price: "400",
    categoryName: "Fauna",
    img: "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/golden-toad-sole-habitat-on-earth-monteverde-mountain-top-news-photo-1607468651.?crop=1xw:1xh;center,top&resize=980:*",
    description: "Lost 40 years ago",
    rating: "3.6",
  },
  {
    _id: uuid(),
    title: "Vulnerable",
    name: "Monarch Butterfly",
    price: "1600",
    categoryName: "Fauna",
    img: "https://files.worldwildlife.org/wwfcmsprod/images/Monarchs_Spring_2020/featured_story/5683rlbl0v_monarchs_spring2020.jpg",
    description: "https://www.youtube.com/watch?v=lWOySU_hAz0",
    rating: "3.9",
  },
  {
    _id: uuid(),
    title: "ENDANGERED",
    name: "Tiger",
    price: "1500",
    categoryName: "Fauna",
    img: "https://cdn.britannica.com/71/174271-050-B90CC219/Siberian-tiger-Longleat-Safari-Adventure-Park-England.jpg?q=60",
    description: "Only 4000 left in the wild",
    rating: "5.0",
  },

  {
    _id: uuid(),
    title: "EXTINCT",
    name: "Dodo",
    price: "300",
    categoryName: "Fauna",
    img: "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/dodo-raphus-cucullatus-didus-ineptus-extinct-flightless-news-photo-1607528588.?crop=1.00xw:0.871xh;0,0.0222xh&resize=980:*",
    description: "Lost 370 years ago",
    rating: "2.4",
  },
  {
    _id: uuid(),
    title: "ENDANGERED",
    name: "Blue Whale",
    price: "2000",
    categoryName: "Fauna",
    img: "https://cdn.britannica.com/73/161673-050-7071CE8B/boat-blue-whale-Sea-of-Cortez-Mexico.jpg?q=60",
    description: "Only 25000 roam the oceans",
    rating: "3.7",
  },
  {
    _id: uuid(),
    title: "Vulnerable",
    name: "Dugong",
    price: "800",
    categoryName: "Fauna",
    img: "https://files.worldwildlife.org/wwfcmsprod/images/Dugong_swimming/hero_full/1k8mrfg9gr_Medium_WW1221.jpg",
    description: "Also called the 'Sea-cows'",
    rating: "3.1",
  },
  {
    _id: uuid(),
    title: "Vulnerable",
    name: "Giant Tortoise",
    price: "1800",
    categoryName: "Fauna",
    img: "https://files.worldwildlife.org/wwfcmsprod/images/HERO_Giant_Tortoise/hero_full/4erl8edrbp_Medium_WW288394.jpg",
    description: "Natives of Galapagos Islands",
    rating: "2.9",
  },
  {
    _id: uuid(),
    title: "Vulnerable",
    name: "Pangolin",
    price: "200",
    categoryName: "Fauna",
    img: "https://files.worldwildlife.org/wwfcmsprod/images/Pangolin_curled_up/portrait_overview/1thbwthr4f_shutterstock_215851909.jpg",
    description: "Highly smuggled across",
    rating: "2.1",
  },
  {
    _id: uuid(),
    title: "ENDANGERED",
    name: "Snow Leopard",
    price: "1200",
    categoryName: "Fauna",
    img: "https://cdn.britannica.com/52/170952-050-A545E35D/carnivore-Snow-leopard-regions-subcontinent-Asia-Indian.jpg?q=60",
    description: "Fewer than 6500 left",
    rating: "4.6",
  },
  {
    _id: uuid(),
    title: "ENDANGERED",
    name: "Whooping Crane",
    price: "900",
    categoryName: "Fauna",
    img: "https://cdn.britannica.com/68/100268-004-DDE6C0EF/Whooping-cranes-International-Crane-Foundation-Baraboo-Wisconsin.jpg?q=60",
    description: "Nearly 400 left",
    rating: "2.8",
  },
  {
    _id: uuid(),
    title: "EXTINCT",
    name: "White Rhino",
    price: "1000",
    categoryName: "Fauna",
    img: "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/najin-and-her-offspring-fatu-two-female-northern-white-news-photo-1607463656.?crop=1xw:1xh;center,top&resize=980:*",
    description: "Lost 2 years ago",
    rating: "4.4",
  },
];
